pipeline {
    agent any
    stages {

        stage('Call Endpoint') {

            steps {

                script {

                    def endpointURL = 'https://localhost:9164/management/applications?carbonAppName=helloWorldCompositeExporter'  // Replace with your actual endpoint URL

                    def response = sh(script: "curl -k -X GET $endpointURL", returnStatus: true)


                    if (response == 0) {

                        echo "Endpoint call successful"

                    } else {

                        error "Endpoint call failed with status code: $response"

                    }

                }

            }

        }

    }

 

    post {

        success {

            // Define actions to take on successful build

        }

        failure {

            // Define actions to take on build failure

        }

    }

}

