pipeline {
    agent any

    stages {
        stage('Call HTTP Endpoint') {
            steps {
                script {
		def endpointURL = 'https://localhost:9164/management/applications?carbonAppName=helloWorldCompositeExporter'  // Replace with your actual endpoint URL
                    def response1 = sh(script: "curl -k -X GET $endpointURL", returnStatus: true)	
                    def response = httpRequest(
                        acceptType: 'APPLICATION_JSON',  // Expected response type
                        contentType: 'APPLICATION_JSON', // Request content type
                        httpMode: 'GET',                // HTTP method (GET, POST, etc.)
                        url: 'https://localhost:9164/management/applications?carbonAppName=helloWorldCompositeExporter', // URL of the endpoint
                        validResponseCodes: '200',      // Expected HTTP response code(s)
                        responseHandle: 'NONE'          // How to handle the response (NONE, JSON, XML, etc.)
                    )
 // Get the HTTP response status code
                    def statusCode = response.getStatus()

                    
                   def responseBody = response.getContent()

                    // Print the status code and status text to the console
                    echo "Response Code: ${statusCode}"
                    echo "Response Body: ${responseBody}"
                }
            }
        }

        // Add more stages as needed
    }
}